env:
  GIT_COMMIT: ${{ github.SHA }}

name: hello-world
on: push
jobs:
  docker-build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    permissions: 
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check where we are and what we have
        run: ls
      - name: Build & Push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.actor }}/xovis-api:1.0-${{ github.sha }},ghcr.io/${{ github.actor }}/xovis-api:latest
  test:
    runs-on: ubuntu-latest
    needs: [docker-build]
    steps:
      - name: Test
        run: echo "I am testing"